### ISSUE TITLE
KeyError: 'querry'

### ISSUE THREAD

**Issue by jianshu93** [MrOlm/bacterialEvolutionMetrics#1]
I have the following error running using this command: 
python dnds_from_drep.py -wd ~/pico/archaea_Poseidoniales/pico/pico_archaea_goANI_dRep -p 48

error:

Pooling 0 dN/dS commands (which take ~5 min each)...
finished chunk 0
Base calculations done- output saved to /vd03/home/jianshu/pico/archaea_Poseidoniales/pico/pico_archaea_goANI_dRep/data/dNdS_data/detailed_dNdS_info.csv
Traceback (most recent call last):
  File "dnds_from_drep.py", line 888, in <module>
    main(args)
  File "dnds_from_drep.py", line 70, in main
    dnds_from_dRep(wd, p=args.processes, debug=args.debug)
  File "dnds_from_drep.py", line 131, in dnds_from_dRep
    GDdb = parse_to_genomeLevel(Rdb)
  File "dnds_from_drep.py", line 138, in parse_to_genomeLevel
    for query, qdb in Ddb.groupby('querry'):
  File "/vd03/home/jianshu/anaconda33/install_with_tear/envs/python3/lib/python3.6/site-packages/pandas/core/frame.py", line 5810, in groupby
    observed=observed,
  File "/vd03/home/jianshu/anaconda33/install_with_tear/envs/python3/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 410, in __init__
    mutated=self.mutated,
  File "/vd03/home/jianshu/anaconda33/install_with_tear/envs/python3/lib/python3.6/site-packages/pandas/core/groupby/grouper.py", line 600, in get_grouper
    raise KeyError(gpr)
KeyError: 'querry'

**Comment by MrOlm** [comment]
It looks like it wasn't able to find any goANI comparisons to calculate dN/dS for. Were any secondary comparisons run? It might make sense to run dRep with `--skipMash` in order to make sure all genomes are compared with goANI.

Best,
Matt

**Comment by jianshu93** [comment]
thanks，i do the same as you sughested

________________________________
